### PR TITLE
Add setup guide for serving locally

### LINKED ISSUE #4: Add setup guide
Add instructions for setting up Jekyll and previewing the site locally.

### PR DESCRIPTION
**Pull request by jonmaddock**
Closes #4. Adding a guide to setup for serving the site locally for previewing changes.

### CODE REVIEW

**Comment by jonmaddock** [comment]
@jholloc can you let me know if these steps work for you?

**Comment by jonmaddock** [comment]
@jholloc could you review this please?

**Comment by jholloc** [comment]
> @jholloc could you review this please?

We need to add "webrick" to the Gemfile to make it work on newer versions of ruby, otherwise it worked fine.

**Comment by jonmaddock** [comment]
@jholloc I'm guessing this is your problem: https://github.com/github/pages-gem/issues/752. One of the solutions suggested is to add:
```
ruby versions["ruby"]
```
to the `Gemfile`; apparently this tells `bundler` to use the `ruby` version used by `github-pages`. This might be a more complete solution than the `webrick` one, if anything else breaks again, or until this problem is fixed by Github Pages. Can you try this out and add the line to the `Gemfile` if it works?

**Comment by jonmaddock** [comment]
Also, was `jekyll` installed using the steps in these instructions (I think `bundle install` installs it as a dependency), or did you have to install it separately? I should add it as a step if not.

**Comment by jonmaddock** [comment]
> Also, was `jekyll` installed using the steps in these instructions (I think `bundle install` installs it as a dependency), or did you have to install it separately? I should add it as a step if not.

`jekyll` was installed by `bundler` as a dependency, so it isn't required as a separate step.

**Comment by jonmaddock** [comment]
Added `webrick` dependency for later Ruby versions.

Have run through instructions from scratch and they appear to work fine.

**Pull request merged**
